# Generated by Django 3.1.4 on 2021-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
